packages:
  - upload-action

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@filoz/*"
  - "@filecoin-project/squid-evm-funding"
onlyBuiltDependencies:
  - esbuild
  - node-datachannel
  - playwright
