name: release-please

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Required for OIDC
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          # PAT so release PRs trigger other workflows (auto-label, add-issues-and-prs-to-fs-project-board).
          # This PAT has the permissions outlined in https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions.
          # Using GITHUB_TOKEN suppresses follow-on workflow runs, which would mean release please PRs wouldn't get properly labeled and added to the project board.
          token: ${{ secrets.FILOZZY_RELEASE_PLEASE_PAT }}
          config-file: release-please-config.json

      # The following steps only run if a release is created
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v6

      - name: Set up pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          run_install: false

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm install -g npm@latest

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --access public
