name: Test upload action
on:
  push:
  pull_request:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Filecoin
        uses: ./upload-action
        with:
          path: ./src
          walletPrivateKey: 0x000000000000000000000000000000000000dead
          network: calibration
          dryRun: true
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload to Filecoin
        uses: ./upload-action
        with:
          path: ./src
          walletPrivateKey: ${{ secrets.WALLET_PRIVATE_KEY }}
          network: calibration
