name: Test upload action
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        dry-run: [true, false]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Filecoin
        uses: ./upload-action
        with:
          path: .
          walletPrivateKey: ${{ secrets.WALLET_PRIVATE_KEY }}
          network: calibration
          dryRun: ${{ matrix.dry-run }}
